2022-09-20 02:08:50,755 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 7206294ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 04:09:40,394 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 7209622ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 06:10:28,706 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 7207622ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 07:17:46,758 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 3997625ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 07:46:51,183 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 243897ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 08:00:53,641 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 801678ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 08:02:43,621 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 69586ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 08:18:35,633 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 911618ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 08:34:27,647 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 911193ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 08:52:33,599 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 1045616ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 09:09:34,915 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 901244ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 09:14:29,259 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 253901ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 09:24:44,126 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 486181ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 09:59:43,192 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 158439ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 10:55:08,119 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 465317ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 11:05:41,306 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 532458ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 11:10:19,901 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 238195ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 12:03:22,170 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 3141828ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 12:07:50,021 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 227476ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 12:09:43,640 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 73237ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 12:51:19,349 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 115255ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 12:55:47,459 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 227748ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 13:00:39,678 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 231828ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 13:10:01,987 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 81950ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 13:24:16,192 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 473263ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 13:45:41,398 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 104933ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 14:19:39,000 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 162423ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 14:26:00,360 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 140733ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 14:39:53,772 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 133228ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 14:50:04,160 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 589232ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 14:54:40,352 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 215785ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 15:01:00,759 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 240362ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 17:01:48,711 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 7207876ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 18:24:31,621 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 4922027ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 18:29:40,971 ERROR 88096 nodejs.ClusterClientNoResponseError: client no response in 228923ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 88096
hostname: hahas-MBP.lan

2022-09-20 19:17:09,167 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 73378ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 19:45:57,630 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 1687839ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 20:03:26,639 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 1008584ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 20:21:37,604 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 1050599ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 20:45:18,657 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 1340593ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 21:03:31,681 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 1052546ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 21:22:06,673 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 1074610ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 21:48:06,658 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 1499588ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 22:27:17,521 ERROR 7723 nodejs.ClusterClientNoResponseError: client no response in 2310482ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/haha/Documents/react/react_blog2/service4/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
name: "ClusterClientNoResponseError"
pid: 7723
hostname: hahas-MBP.lan

2022-09-20 22:57:02,896 ERROR 9644 [-/127.0.0.1/-/175ms POST /default/addComment] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'articleId' in 'field list'
    at Query.Sequence._packetToError (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:65:19)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:54:5
    sql: INSERT INTO `comments`(`userId`, `articleId`, `connent`, `addTime`, `like`) VALUES(1, 2, '22', '2022-09-20 22:57', 0)
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'articleId' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `comments`(`userId`, `articleId`, `connent`, `addTime`, `like`) VALUES(1, 2, '22', '2022-09-20 22:57', 0)"
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 9644
hostname: hahas-MBP.lan

2022-09-20 22:59:36,089 ERROR 9644 [-/127.0.0.1/-/149ms POST /default/addComment] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'connent' in 'field list'
    at Query.Sequence._packetToError (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:65:19)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:54:5
    sql: INSERT INTO `comments`(`userId`, `article_id`, `connent`, `addTime`, `like`, `userName`) VALUES(1, 2, '22', '2022-09-20 22:59', 0, 'j')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'connent' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `comments`(`userId`, `article_id`, `connent`, `addTime`, `like`, `userName`) VALUES(1, 2, '22', '2022-09-20 22:59', 0, 'j')"
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 9644
hostname: hahas-MBP.lan

2022-09-20 23:00:06,363 ERROR 9644 [-/127.0.0.1/-/146ms POST /default/addComment] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'like' in 'field list'
    at Query.Sequence._packetToError (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Pool.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/mysql/lib/Pool.js:199:23)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:12:10)
    at Pool.ret [as query] (/Users/haha/Documents/react/react_blog2/service4/node_modules/pify/index.js:56:34)
    at RDSClient.proto._query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/client.js:38:20)
    at RDSClient.proto.query (/Users/haha/Documents/react/react_blog2/service4/node_modules/ali-rds/lib/operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (/Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:65:19)
    at /Users/haha/Documents/react/react_blog2/service4/node_modules/co/index.js:54:5
    sql: INSERT INTO `comments`(`userId`, `article_id`, `content`, `addTime`, `like`, `userName`) VALUES(1, 2, '22', '2022-09-20 23:00', 0, 'j')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'like' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `comments`(`userId`, `article_id`, `content`, `addTime`, `like`, `userName`) VALUES(1, 2, '22', '2022-09-20 23:00', 0, 'j')"
headers: {"Access-Control-Allow-Origin":"http://localhost:3000","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 9644
hostname: hahas-MBP.lan

